spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.110:3306/sell?characterEncoding=utf-8&userSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
  port: 8083


#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat
#  file: /var/log/tomcat/sell.log
#  level: debug