spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#    jdbc-url: jdbc:mysql://192.168.0.110:3306/sell?characterEncoding=utf-8&userSSL=false8&serverTimezone=UTC
    jdbc-url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&userSSL=false8&serverTimezone=UTC
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
  port: 8083




#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat
#  file: /var/log/tomcat/sell.log
#  level: debug